/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/sessions": {
    post: operations["createSession"];
  };
  "/api/v1/users": {
    post: operations["createUser"];
  };
  "/api/v1/cards/{cardNumber}:checkCardState": {
    get: operations["checkCardState"];
  };
}

export interface components {
  schemas: {
    HttpError: {
      message?: string;
      status?: number;
      errorCode?: string;
      errorData?: {
        message?: string;
        code?: string;
      };
      errorClass?: string;
      stack?: string;
    };
    U4000: {
      /** @example U4000 */
      code?: string;
    };
    U4001: {
      /** @example U4001 */
      code?: string;
    };
    U4002: {
      /** @example U4002 */
      code?: string;
    };
  };
  responses: {
    /** Unauthorized access */
    UnauthorizedErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
    /** Unauthorized access */
    NotAuthenticatedErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
    /** Request not processed - bad_request */
    BadRequestErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
    /** Entity not found - not_found */
    NotFoundErrorResponse: {
      content: {
        "application/json": components["schemas"]["HttpError"];
      };
    };
  };
}

export interface operations {
  createSession: {
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": {
            /** @example caeb2a6a-bd1d-41cc-bfdf-5d4514ace591 */
            token: string;
          };
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
      401: components["responses"]["NotAuthenticatedErrorResponse"];
      404: components["responses"]["NotFoundErrorResponse"];
    };
    requestBody: {
      content: {
        "application/json": {
          user: {
            /** @example john@doe.com */
            name: string;
            /** @example myPassword */
            passwd: string;
          };
        };
      };
    };
  };
  createUser: {
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": {
            /** @example caeb2a6a-bd1d-41cc-bfdf-5d4514ace591 */
            token: string;
          };
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
      /** Invalid data */
      422: {
        content: {
          "application/json": Partial<components["schemas"]["U4000"]> &
            Partial<components["schemas"]["U4001"]> &
            Partial<components["schemas"]["U4002"]>;
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          user: {
            /** @example john@doe.com */
            name: string;
            /** @example myPassword */
            passwd: string;
          };
        };
      };
    };
  };
  checkCardState: {
    parameters: {
      path: {
        /** Unique card number. */
        cardNumber: string;
      };
    };
    responses: {
      /** ok */
      200: {
        content: {
          "application/json": {
            card?: {
              /** Format: Date */
              validUntil?: string;
              /** @example valid */
              state?: string;
            };
          };
        };
      };
      400: components["responses"]["BadRequestErrorResponse"];
      401: components["responses"]["NotAuthenticatedErrorResponse"];
      403: components["responses"]["UnauthorizedErrorResponse"];
    };
  };
}

export interface external {}
