name: Deploy
on: 
  workflow_call:
jobs:
  deploy:
    env:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      INPUT_PASSWORD: ${{ secrets.INPUT_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Print branch name
        run: echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: Deploy to DigitalOcean Droplet
        if: steps.branch-name.outputs.current_branch == 'master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          password: ${{ env.INPUT_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
